[package]
name = "justcsv"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Kalashnikov"]
description = "Simple CSV-file reader/writer"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
nom = "7"
